@ECHO OFF
set main_docs=https://kdocs.cn/l/cune7WAK6oZX
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set link=https://yuelove.lanzouj.com/
set lzdl=https://eebbk-boom.github.io/EEBBK_profile/bin/lzdl.7z
set bff=%link%ivDrM13r94af
set magisk=%link%iaWNP13r8mvi
set elf=%link%ixoNO13r8mda
set toolbox=https://lanzouj.com/ivt3r138wyji
set key_bff=T3TE
set key_magisk=T3TE
set key_elf=T3TE
set magisk_vercode=26100
set elf_vercode=T3_elf
set checksum_bff=F73E44F2
set checksum_magisk=5B63322A
set checksum_elf=1285D92E
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
