@ECHO OFF
set main_docs=https://kdocs.cn/l/cune7WAK6oZX
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set link=https://yuelove.lanzouj.com/
set link2=https://ycly.lanzoui.com/
set lzdl=https://eebbk-boom.github.io/EEBBK_profile/bin/lzdl.7z
set bff=%link%ivoep157g15g
set magisk=%link%iaWNP13r8mvi
set elf=%link%ixoNO13r8mda
set toolbox=%link2%ivt3r138wyji
set driver=%link2%iEPJm15796ti
set update_log=%link2%iS7Lx157h74h
set key_bff=T3TE
set key_magisk=T3TE
set key_elf=T3TE
set key_driver=T3TE
set magisk_vercode=25200
set checksum_bff=2A31F360
set checksum_magisk=5B63322A
set checksum_elf=1285D92E
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
