@ECHO OFF
set link=https://ycly.lanzn.com/
set main_docs=https://kdocs.cn/l/cbjtVlrpWOtF
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set stock_boot=%link%iIgnN12vgf1c
set twrp=%link%iKZTK16qhczi
set misc=%link%ilyKX1541zgd
set toolbox=%link%iX1Fa17qt5sh
set magisk=%link%iuhRL1nrxlta
set adb=%link%i0nal13buumd
set elf=prog_emmc_firehose_Sdm660_ddr.elf
set twrp_file=twrp-3.7.0_9-20230827-H7000.img
set lzdl=https://down.eebbk.top/bin/lzdl.7z
set checksum_twrp=0BF7EFF4
set checksum_boot=4DA4D231
set checksum_magisk=36E02F59
set checksum_adb=6DF5B994
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
