@ECHO OFF
set link=https://ycly.lanzouw.com/
set stock_boot=%link%iIgnN12vgf1c
set twrp=%link%iNulR12sjsuj
set misc=%link%ipxko12vghad
set toolbox=%link%ivt3r138wyji
set magisk=%link%iGboN0xh8r7i
set elf=prog_emmc_firehose_Sdm660_ddr.elf
set lzdl=https://eebbk-boom.github.io/EEBBK_profile/bin/lzdl.7z
set checksum_twrp=4ABC74EF
set checksum_boot=4DA4D231
set checksum_magisk=5B63322A
