@ECHO OFF
set link=https://ycly.lanzouw.com/
set main_docs=https://kdocs.cn/l/cbjtVlrpWOtF
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set stock_boot=%link%iIgnN12vgf1c
set twrp=%link%iKZTK16qhczi
set misc=%link%ilyKX1541zgd
set toolbox=%link%itvaS15uxthg
set magisk=%link%iGboN0xh8r7i
set adb=%link%i0nal13buumd
set elf=prog_emmc_firehose_Sdm660_ddr.elf
set twrp_file=twrp-3.7.0_9-20230827-H7000.img
set lzdl=https://eebbk-boom.github.io/EEBBK_profile/bin/lzdl.7z
set checksum_twrp=0BF7EFF4
set checksum_boot=4DA4D231
set checksum_magisk=5B63322A
set checksum_adb=6DF5B994
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
