@ECHO OFF
set main_docs=https://kdocs.cn/l/cune7WAK6oZX
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set link=https://yuelove.lanzouj.com/
set lzdl=https://down.eebbk.top/bin/lzdl.7z
set bff=%link%iFKCH1is20sd
set magisk=%link%iJyrv15wcq8f
set elf=%link%ixoNO13r8mda
set toolbox=%link%iX1Fa17qt5sh
set driver=%link%iEPJm15796ti
set update_log=%link%i0SVV1is09fc
set logo=%link%iK54c1anp6ub
set key_bff=T3TE
set key_magisk=T3TE
set key_elf=T3TE
set key_driver=1234
set magisk_vercode=25200
set checksum_bff=0BAF9BA4
set checksum_magisk=3A965DEE
set checksum_elf=1285D92E
set checksum_rom=3A965DEE
set checksum_firmware=1285D92E
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
