@ECHO OFF
set main_docs=https://kdocs.cn/l/cune7WAK6oZX
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set link=https://yuelove.lanzv.com/
set lzdl=https://down.eebbk.top/bin/lzdl.7z
set bff=%link%iXJb81mi8eti
set Apatch=%link%iXftQ1mi6cch
set elf=%link%i8Vas1mi7fgf
set toolbox=%link%iX1Fa17qt5sh
set driver=%link%iEPJm15796ti
set update_log=%link%iXBcH1mi1uzi
set logo=%link%iK54c1anp6ub
set keyR=EEBBK-BOOM
set device=H110
set key_bff=S5PTE
set key_Apatch=S5PTE
set key_elf=S5PTE
set key_driver=1234
set Apatch_vercode=apatch
set checksum_bff=0BB3ECC9
set checksum_Apatch=7138C29B
set checksum_elf=B4CE9BBD
set checksum_rom=11A932E0
set checksum_firmware=3B304279
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
