@ECHO OFF
set link=https://ycly.lanzn.com/
set main_docs=https://kdocs.cn/l/cdTOie6LVgAG
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set toolbox=%link%i58ET21zzy4h
set magisk=%link%iuhRL1nrxlta
set spd=%link%iWBeE15lim1e
set pac=%link%iPPEx1544q1c
set folder=%link%iln5S15nlosd
set stock_pac=S1W_stock_V1.4.0_BOOM.pac
set root_pac=S1W_magisk_BOOM.pac
set spd_dir=SPD_Research_Tool
set lzdl=https://down.eebbk.top/bin/lzdl.7z
set checksum_spd=72803FD7
set checksum_stock=E4237790
set checksum_root=6C98202A
set checksum_magisk=36E02F59
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
