@ECHO OFF
set link=https://ycly.lanzouw.com/
set main_docs=https://kdocs.cn/l/cdTOie6LVgAG
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set toolbox=%link%iX1Fa17qt5sh
set magisk=%link%itAp917ok08b
set spd=%link%iWBeE15lim1e
set pac=%link%i9iCC1544q0b
set folder=%link%iln5S15nlosd
set stock_pac=X1_stock_V1.1.0_BOOM.pac
set root_pac=X1_magisk_BOOM.pac
set spd_dir=SPD_Research_Tool
set lzdl=https://down.eebbk.top/bin/lzdl.7z
set checksum_spd=72803FD7
set checksum_stock=1C6A2C42
set checksum_root=D72716AD
set checksum_magisk=05304293
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
