@ECHO OFF
set link=https://ycly.lanzn.com/
set main_docs=https://kdocs.cn/l/cdTOie6LVgAG
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set toolbox=%link%i58ET21zzy4h
set magisk=%link%iuhRL1nrxlta
set spd=%link%iWBeE15lim1e
set pac=%link%iSRQp220zlde
set folder=%link%iln5S15nlosd
set stock_pac=X1_stock_V1.1.1_BOOM.pac
set root_pac=X1_magisk_V1.1.1_BOOM.pac
set spd_dir=SPD_Research_Tool
set lzdl=https://down.eebbk.top/bin/lzdl.7z
set checksum_spd=72803FD7
set checksum_stock=EBA866B2
set checksum_root=F7E7729B
set checksum_magisk=36E02F59
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
