@ECHO OFF
set link=https://ycly.lanzouw.com/
set main_docs=https://kdocs.cn/l/cbjtVlrpWOtF
set block_docs=https://kdocs.cn/l/cune7WAK6oZX
set stock_boot=%link%i7w91161r5zg
set twrp=%link%iJRdg161r5vc
set mtkclient=%link%irMur15xwc2b
set python=%link%iOc52161qx6j
set toolbox=%link%itvaS15uxthg
set magisk=%link%iGboN0xh8r7i
set adb=%link%i0nal13buumd
set twrp_file=twrp-3.7.0_11-20230405-H3000X.img
set mtkclient_dir=mtkclient-main
set pypi=https://repo.huaweicloud.com/repository/pypi/simple/
set lzdl=https://eebbk-boom.github.io/EEBBK_profile/bin/lzdl.7z
set checksum_twrp=A1D720F4
set checksum_boot=AB364E8D
set checksum_magisk=5B63322A
set checksum_adb=6DF5B994
set A=attrib +s +h /s /d
set B=attrib -s -h /s /d
